'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),http=require('node:http'),{spawn}=require('node:child_process'),AdmZip=require('adm-zip'),{analyze}=require('./analyzer');let active=null;const MAX_ENTRY=100*1024*1024;
function safeName(name){const n=name.replace(/\\/g,'/');if(!n||n.startsWith('/')||/^[a-z]:/i.test(n)||n.split('/').some(x=>x==='..'||x==='.')||n.includes('\0'))throw Error('Unsafe ZIP path');return n}
function unpack(z){analyze(z);const workspace=fs.mkdtempSync(path.join(os.tmpdir(),'applab-'));try{for(const e of new AdmZip(z).getEntries()){const n=safeName(e.entryName),d=path.resolve(workspace,n);if(!d.startsWith(workspace+path.sep))throw Error('Unsafe ZIP path');if(e.isDirectory){fs.mkdirSync(d,{recursive:true});continue}if(e.header.size>MAX_ENTRY)throw Error('File too large');fs.mkdirSync(path.dirname(d),{recursive:true});fs.writeFileSync(d,e.getData(),{flag:'wx'})}let root=workspace;for(let i=0;i<4;i++){if(fs.existsSync(path.join(root,'index.html'))||fs.existsSync(path.join(root,'package.json')))break;const a=fs.readdirSync(root,{withFileTypes:true}).filter(x=>x.isDirectory()&&!x.name.startsWith('__MACOSX'));if(a.length!==1)break;root=path.join(root,a[0].name)}return{workspace,root}}catch(e){fs.rmSync(workspace,{recursive:true,force:true});throw e}}
function projectType(root){let pkg=null;const f=path.join(root,'package.json');if(fs.existsSync(f)){try{pkg=JSON.parse(fs.readFileSync(f,'utf8'))}catch{throw Error('Invalid package.json')}}return{kind:pkg?'node':'static',scripts:pkg?.scripts||{},hasIndex:fs.existsSync(path.join(root,'index.html'))}}
function mime(f){return({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.ico':'image/x-icon','.woff2':'font/woff2'})[path.extname(f).toLowerCase()]||'application/octet-stream'}
function staticServer(root){const base=fs.realpathSync(root),server=http.createServer((req,res)=>{try{const u=new URL(req.url,'http://localhost'),d=decodeURIComponent(u.pathname);if(d.includes('\0')||d.includes('\\')||d.split('/').includes('..')){res.writeHead(403);return res.end()}let f=path.resolve(base,'.'+d);if(!f.startsWith(base+path.sep)&&f!==base){res.writeHead(403);return res.end()}if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');if(!fs.existsSync(f)&&!path.extname(d))f=path.join(base,'index.html');if(!fs.existsSync(f)||!fs.statSync(f).isFile()){res.writeHead(404);return res.end('Not found')}res.setHeader('Content-Type',mime(f));res.setHeader('Cache-Control','no-store');fs.createReadStream(f).pipe(res)}catch{res.writeHead(400);res.end('Invalid request')}});return new Promise((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',()=>resolve({server,url:'http://127.0.0.1:'+server.address().port}))})}
function cmd(n){return process.platform==='win32'?n+'.cmd':n}function killTree(child){if(!child)return;if(process.platform==='win32')spawn('taskkill',['/pid',String(child.pid),'/t','/f'],{windowsHide:true});else child.kill('SIGTERM')}
async function stop(){if(!active)return;const a=active;active=null;if(a.child)killTree(a.child);if(a.server)await new Promise(r=>a.server.close(r));if(a.workspace)try{fs.rmSync(a.workspace,{recursive:true,force:true,maxRetries:5,retryDelay:150})}catch{}}
function run(bin,args,cwd,onLog,timeout=300000){return new Promise((resolve,reject)=>{const child=spawn(bin,args,{cwd,shell:false,windowsHide:true,env:{...process.env,CI:'true'}});active.child=child;const timer=setTimeout(()=>{killTree(child);reject(Error('Process timed out'))},timeout);for(const s of [child.stdout,child.stderr])s.on('data',x=>onLog(String(x).slice(0,5000)));child.once('error',e=>{clearTimeout(timer);reject(e)});child.once('close',code=>{clearTimeout(timer);if(active)active.child=null;code===0?resolve():reject(Error(args.join(' ')+' failed with exit code '+code))})})}
async function startStatic(z){await stop();const p=unpack(z);try{if(!projectType(p.root).hasIndex)throw Error('No index.html found. Use Build & Preview or Netlify Local.');const r=await staticServer(p.root);active={...p,...r};return{url:r.url,message:'Static preview running.'}}catch(e){fs.rmSync(p.workspace,{recursive:true,force:true});throw e}}
function waitUrl(child,onLog){return new Promise((resolve,reject)=>{let buf='',done=false;const finish=(e,u)=>{if(done)return;done=true;clearTimeout(t);e?reject(e):resolve(u)};const scan=x=>{const s=String(x);onLog(s.slice(0,5000));buf=(buf+s).slice(-40000);const m=[...buf.matchAll(/https?:\/\/(?:127\.0\.0\.1|localhost):\d+/g)];if(m.length)finish(null,m.at(-1)[0].replace('localhost','127.0.0.1'))};child.stdout.on('data',scan);child.stderr.on('data',scan);child.once('error',finish);child.once('close',c=>finish(Error('Local runtime stopped with exit code '+c)));const t=setTimeout(()=>finish(Error('Local runtime did not become ready in 3 minutes')),180000)})}
async function startNetlify(z,onLog){await stop();const p=unpack(z);active={...p};try{if(projectType(p.root).kind==='node'){const args=fs.existsSync(path.join(p.root,'package-lock.json'))?['ci','--no-audit','--no-fund']:['install','--no-audit','--no-fund'];onLog('Installing project dependencies…\n');await run(cmd('npm'),args,p.root,onLog)}onLog('Starting Netlify Dev…\n');const child=spawn(cmd('npx'),['--yes','netlify-cli@latest','dev'],{cwd:p.root,shell:false,windowsHide:true,env:{...process.env,CI:'true',BROWSER:'none'}});active.child=child;const url=await waitUrl(child,onLog);active={...p,child};return{url,message:'Netlify Dev local runtime is running.'}}catch(e){await stop();throw e}}
async function startBuilt(z,onLog){await stop();const report=analyze(z),p=unpack(z);active={...p};try{const t=projectType(p.root);if(t.kind!=='node'||!t.scripts.build)throw Error('No build script found in package.json');const args=fs.existsSync(path.join(p.root,'package-lock.json'))?['ci','--no-audit','--no-fund']:['install','--no-audit','--no-fund'];await run(cmd('npm'),args,p.root,onLog);await run(cmd('npm'),['run','build'],p.root,onLog);const configured=report.project.publishDir&&path.resolve(p.root,report.project.publishDir),c=[configured,...['dist','build','out','public'].map(x=>path.join(p.root,x))].filter(Boolean),out=c.find(x=>x.startsWith(p.root)&&fs.existsSync(path.join(x,'index.html')));if(!out)throw Error('Build finished but no static index.html output was found. Try Netlify Local for SSR/framework runtime.');const r=await staticServer(out);active={...p,...r};return{url:r.url,message:'Production build preview running.'}}catch(e){await stop();throw e}}
module.exports={safeName,projectType,staticServer,startStatic,startNetlify,startBuilt,stop};